services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
       ME_CONFIG_MONGODB_ADMINPASSWORD: admin
       ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - mongo-network


  library-app:
    image: library-app
    container_name: library
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb
    networks:
      - mongo-network


volumes:
  data: {}

networks:
  mongo-network:
    driver: bridge
